### ISSUE TITLE
Gradle implementation does not resolve

### ISSUE THREAD

**Issue by kjbaker-uk** [aagarwal1012/Image-Steganography-Library-Android#14]
**Describe the bug**
I have tried to follow your instructions to add your library to my project, When I add "implementation 'com.github.aagarwal1012:Image-Steganography-Library-Android:v1.0'" into the build.gradle I get the following error.

ERROR: Failed to resolve: com.github.aagarwal1012:Image-Steganography-Library-Android:v1.0

My build environment.
Android Studio 3.6 Canary 5
Build #AI-191.7479.19.36.5721125, built on July 11, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-25-generic

**Comment by kjbaker-uk** [comment]
Fixed. I was being stupid.

**Comment by Om3rjs** [comment]
how did you fixed it?

**Comment by jefmat167** [comment]
> Fixed. I was being stupid.

How did you fix it? I'm having the same issue

**Comment by kjbaker-uk** [comment]
Sorry just seen these messages. I actually don't remember. I will load up the project and have a look.

**Comment by jefmat167** [comment]
> Sorry just seen these messages. I actually don't remember. I will load up the project and have a look.

Alright. Will be waiting for feedback.
