### ISSUE TITLE
Whatsapp and telegram delete the message.

### ISSUE THREAD

**Issue by CROCDC** [aagarwal1012/Image-Steganography-Library-Android#2]
The problem is found when you share the encoded image is shared with both app.
When I downloaded the same image again, I found that both applications deleted the message

regards

**Comment by aagarwal1012** [comment]
@CROCDC can you please describe the problem in a detailed manner, so that it includes the errors message and steps to reproduce the problem.
Thanks for raising the issue 👍

**Comment by CROCDC** [comment]
the error is that the image is not decoded and for the same thing to happen you must share a coded image through whatsapp or telegram and then decode the image. You will find that the shared image can not be encoded

**Comment by aagarwal1012** [comment]
@CROCDC actually when we send the image via WhatsApp, it tries to compress the image so to make the size of it smaller. Therefore, the encoded message is lost in the transmission as it alters the pixels of the image. Try to use platforms like google drive, facebook, etc. which do not alter the image in the transmission.
Hope you understand 😄

**Comment by CROCDC** [comment]
If I imagined I had to do with the best propeller that makes you whatsapp to the images. I think there is a way to avoid compression or that there is another way to introduce data in the image?

**Comment by aagarwal1012** [comment]
@CROCDC you can follow this link, [https://www.techbii.com/send-full-resolution-whatsapp-image/](https://www.techbii.com/send-full-resolution-whatsapp-image/)
I will suggest using the first method in the link given as it is easily achievable in android.

**Comment by CROCDC** [comment]
thank you so much sorry for the inconvenience

**Comment by aagarwal1012** [comment]
No problem @CROCDC  🙅‍♂️ You can ask for the help anytime.
I think that this `issue` is resolved now, so I am **closing** this issue.
