### ISSUE TITLE
Hanging at save

### ISSUE THREAD

**Issue by rhayes2** [aagarwal1012/Image-Steganography-Library-Android#5]
After encoding an Image.
 Hitting save causes system to hang and the file isnt saved.

PR:[#4](https://github.com/aagarwal1012/Image-Steganography-Library-Android/pull/4)

**Comment by TheinvinciblePrints** [comment]
Facing same issue...please help resolve urgently

**Comment by rhayes2** [comment]
Its in my PR, Try it out before I / We merge! :)

**Comment by rhayes2** [comment]
Here's a link to my forkif you want to try it [https://github.com/rhayes2/Image-Steganography-Library-Android](url)

**Comment by aagarwal1012** [comment]
@rhayes2, please draft a new release.
